# Generated by Django 5.2.4 on 2026-01-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_salarystructure_payrollrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='loans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='nssf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='loans',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Loan repayments', max_digits=10),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='nssf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NSSF contribution', max_digits=10),
        ),
    ]
