# Generated by Django 5.2.4 on 2026-01-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payrollrecord_loans_payrollrecord_nssf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='advances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salary advances deducted', max_digits=10),
        ),
    ]
