# Generated by Django 5.2.4 on 2026-01-24 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_schoolconfig_options_schoolconfig_admin'),
        ('finance', '0004_payrollrecord_advances'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='studentfinanceaccount',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='config.schoolconfig'),
        ),
    ]
