# Generated by Django 5.2.4 on 2026-01-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='EduManage Academy', max_length=200)),
                ('school_code', models.CharField(default='EDU', max_length=20)),
                ('school_email', models.EmailField(default='info@school.com', max_length=254)),
                ('school_phone', models.CharField(default='+254700000000', max_length=20)),
                ('admission_number_format', models.CharField(default='{SCHOOL_CODE}/{YEAR}/{COUNTER:04d}', help_text='Format: {SCHOOL_CODE}, {YEAR}, {COUNTER:04d}, {GRADE}. Example: EDU/2024/0001', max_length=100)),
                ('admission_counter', models.IntegerField(default=0, help_text='Auto-incremented counter for admission numbers')),
                ('current_term', models.CharField(default='TERM_1', max_length=20)),
                ('current_year', models.IntegerField(default=2024)),
                ('default_currency', models.CharField(default='KES', max_length=10)),
            ],
            options={
                'verbose_name': 'School Configuration',
                'verbose_name_plural': 'School Configuration',
            },
        ),
    ]
