# Generated by Django 5.2.4 on 2026-01-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='school_address',
            field=models.TextField(default='P.O Box 123-00100, Nairobi'),
        ),
    ]
