# Generated by Django 5.2.4 on 2026-01-24 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_schoolconfig_school_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolconfig',
            options={'verbose_name': 'School Configuration', 'verbose_name_plural': 'School Configurations'},
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_config', to=settings.AUTH_USER_MODEL),
        ),
    ]
