# Generated by Django 5.2.4 on 2026-01-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_schoolconfig_options_schoolconfig_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='portal_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
