# Generated by Django 5.2.4 on 2026-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_schoolconfig_portal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='accountant_portal_password',
            field=models.CharField(default='Finance@123', max_length=128),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='driver_portal_password',
            field=models.CharField(default='Driver@123', max_length=128),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='food_portal_password',
            field=models.CharField(default='Food@123', max_length=128),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='student_portal_password',
            field=models.CharField(default='Student@123', max_length=128),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='teacher_portal_password',
            field=models.CharField(default='Teacher@123', max_length=128),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='transport_portal_password',
            field=models.CharField(default='Transport@123', max_length=128),
        ),
    ]
