# Generated by Django 5.2.4 on 2026-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_schoolconfig_accountant_portal_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
