# Generated by Django 5.2.4 on 2026-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_schoolconfig_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='subscription_plan',
            field=models.CharField(default='Basic', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='subscription_status',
            field=models.CharField(default='Trial', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
