# Generated by Django 5.2.4 on 2026-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_schoolconfig_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
