# Generated by Django 5.2.4 on 2026-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_subscriptionpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=True)),
                ('debug_mode', models.BooleanField(default=False)),
                ('allow_api_access', models.BooleanField(default=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('trial_days', models.IntegerField(default=14)),
                ('basic_price', models.DecimalField(decimal_places=2, default=2999.0, max_digits=10)),
                ('standard_price', models.DecimalField(decimal_places=2, default=5999.0, max_digits=10)),
                ('enterprise_price', models.DecimalField(decimal_places=2, default=14999.0, max_digits=10)),
                ('sms_gateway', models.CharField(default='AfricasTalking', max_length=50)),
                ('sms_active', models.BooleanField(default=True)),
                ('email_active', models.BooleanField(default=True)),
                ('force_2fa_admins', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'System Global Settings',
                'verbose_name_plural': 'System Global Settings',
            },
        ),
    ]
