# Generated by Django 5.1.3 on 2025-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='term1_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Term 1 fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='grade',
            name='term2_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Term 2 fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='grade',
            name='term3_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Term 3 fees', max_digits=10),
        ),
    ]
