# Generated by Django 5.1.3 on 2025-02-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_grade_term1_fees_grade_term2_fees_grade_term3_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='term1_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Term 1 fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='term2_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Term 2 fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='term3_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Term 3 fees', max_digits=10),
        ),
    ]
