# Generated by Django 5.1.3 on 2025-02-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_student_term1_fees_student_term2_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], default=1),
            preserve_default=False,
        ),
    ]
