# Generated by Django 4.2.17 on 2025-02-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_payment_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='recipient_type',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('STAFF', 'All Staff'), ('TEACHERS', 'All Teachers'), ('STUDENTS', 'All Students'), ('GRADE', 'Specific Grade')], default='ALL', max_length=10),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='schools.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='schools.department'),
        ),
    ]
