# Generated by Django 4.2.17 on 2025-02-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
    ]
