# Generated by Django 4.2.17 on 2025-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
