# Generated by Django 5.1.3 on 2025-06-05 13:42

from django.db import migrations, models


def remove_duplicate_assessments(apps, schema_editor):
    """
    Remove duplicate assessment records to prepare for unique constraint.
    Keep the most recent assessment for each student-assessment_type-term combination.
    """
    Assessment = apps.get_model('schools', 'Assessment')
    
    # Get all assessments grouped by student, assessment_type, and term
    from django.db.models import Max
    
    # Find the latest assessment for each combination
    latest_assessments = Assessment.objects.values(
        'student', 'assessment_type', 'term'
    ).annotate(
        latest_id=Max('id')
    ).values_list('latest_id', flat=True)
    
    # Delete all assessments except the latest ones
    Assessment.objects.exclude(id__in=latest_assessments).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_remove_payment_created_at_remove_payment_description_and_more'),
    ]

    operations = [
        # Data migration to remove duplicates
        migrations.RunPython(remove_duplicate_assessments, reverse_code=migrations.RunPython.noop),
        
        migrations.AddField(
            model_name='assessmentresult',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='weekly_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('weekly', 'Weekly Assessment'), ('opener', 'Opener Assessment'), ('mid-term', 'Mid-Term Assessment'), ('end-term', 'End-Term Assessment')], max_length=20),
        ),
    ]
