# Generated by Django 4.2.19 on 2025-08-01 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0011_assessmentresult_marks_assessmentresult_weekly_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.student'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('student', 'assessment_type', 'term')},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='teacher',
        ),
    ]
