# Generated by Django 4.2.19 on 2025-09-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_alter_assessment_created_at_alter_assessment_date_and_more'),
        ('schools', '0012_assessment_week_number_and_constraints'),
    ]

    operations = [
    ]
