# Generated by Django 5.2.4 on 2025-11-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_route_transportfee_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together=set(),
        ),
    ]
