# Generated by Django 5.2.4 on 2025-11-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_foodplan_alter_attendance_student_foodfee_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodfee',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transportfee',
            unique_together=set(),
        ),
    ]
