# Generated by Django 5.2.4 on 2025-11-25 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_remove_unique_constraints_transport_food_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMealPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('TEA_BREAK', 'Tea Break'), ('LUNCH', 'Lunch'), ('FRUITS', 'Fruits')], help_text='Type of meal: Tea Break, Lunch, or Fruits', max_length=20)),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('SEVERAL_DAYS', 'Several Days'), ('INCONSISTENT', 'Inconsistent')], default='MONTHLY', help_text='How often the student pays for this meal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid for this meal', max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer')], default='CASH', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date when payment was made')),
                ('start_date', models.DateField(help_text='Start date for this meal payment period')),
                ('end_date', models.DateField(blank=True, help_text='End date for this meal payment period (if applicable)', null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(help_text='Unique reference number for this payment', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment record is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_payments', to='schools.student')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'meal_type', 'is_active'], name='schools_stu_student_cb8a21_idx'), models.Index(fields=['payment_date'], name='schools_stu_payment_2cdcad_idx')],
            },
        ),
    ]
