# Generated by Django 5.2.4 on 2025-11-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_studentmealpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('TEA_BREAK', 'Tea Break'), ('LUNCH', 'Lunch'), ('FRUITS', 'Fruits')], help_text='Type of meal', max_length=20, unique=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, help_text='Default price per day for this meal', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Meal Pricing',
                'ordering': ['meal_type'],
            },
        ),
        migrations.AddField(
            model_name='studentmealpayment',
            name='number_of_days',
            field=models.IntegerField(default=1, help_text='Number of days this payment covers'),
        ),
        migrations.AddField(
            model_name='studentmealpayment',
            name='payment_group',
            field=models.CharField(blank=True, help_text='Group identifier for payments made together (same transaction)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentmealpayment',
            name='payment_frequency',
            field=models.CharField(choices=[('PER_DAY', 'Per Day'), ('MULTIPLE_DAYS', 'Multiple Days'), ('PER_WEEK', 'Per Week'), ('PER_MONTH', 'Per Month'), ('FULL_TERM', 'Full Term')], default='MULTIPLE_DAYS', help_text='How often the student pays for this meal', max_length=20),
        ),
    ]
