# Generated by Django 5.2.4 on 2025-11-25 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_mealpricing_studentmealpayment_number_of_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmealpayment',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance for this payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='studentmealpayment',
            name='days_consumed',
            field=models.IntegerField(default=0, help_text='Number of days already consumed from this payment'),
        ),
        migrations.AddField(
            model_name='studentmealpayment',
            name='days_remaining',
            field=models.IntegerField(default=0, help_text='Number of days remaining for this payment'),
        ),
        migrations.CreateModel(
            name='MealConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('TEA_BREAK', 'Tea Break'), ('LUNCH', 'Lunch'), ('FRUITS', 'Fruits')], help_text='Type of meal consumed', max_length=20)),
                ('consumption_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the meal was served')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this meal serving')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_payment', models.ForeignKey(help_text='The payment record this consumption is deducted from', on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='schools.studentmealpayment')),
                ('served_by', models.ForeignKey(blank=True, help_text='User who marked the meal as served', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals_served', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_consumptions', to='schools.student')),
            ],
            options={
                'ordering': ['-consumption_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'meal_type', 'consumption_date'], name='schools_mea_student_d067ca_idx'), models.Index(fields=['consumption_date'], name='schools_mea_consump_ba0660_idx')],
                'unique_together': {('student', 'meal_type', 'consumption_date')},
            },
        ),
    ]
