# Generated by Django 5.2.4 on 2025-11-25 10:37

from django.db import migrations


def fix_payment_frequency(apps, schema_editor):
    """Fix invalid payment_frequency values"""
    StudentMealPayment = apps.get_model('schools', 'StudentMealPayment')
    
    # Fix 'SEVERAL_DAYS' to 'MULTIPLE_DAYS'
    StudentMealPayment.objects.filter(payment_frequency='SEVERAL_DAYS').update(
        payment_frequency='MULTIPLE_DAYS'
    )
    
    # Fix any other invalid values
    valid_frequencies = ['PER_DAY', 'MULTIPLE_DAYS', 'PER_WEEK', 'PER_MONTH', 'FULL_TERM']
    StudentMealPayment.objects.exclude(payment_frequency__in=valid_frequencies).update(
        payment_frequency='MULTIPLE_DAYS'
    )


def reverse_fix(apps, schema_editor):
    """Reverse migration - not really needed but required"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_studentmealpayment_balance_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_payment_frequency, reverse_fix),
    ]
