# Generated by Django 5.2.4 on 2025-11-25 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_student_guardian_email_student_guardian_id_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=True)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('pending_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=5, help_text='Minutes between auto-sync attempts')),
                ('max_retry_attempts', models.IntegerField(default=3)),
                ('sync_on_startup', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sync Status',
                'verbose_name_plural': 'Sync Status',
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('model_name', models.CharField(help_text="Name of the model (e.g., 'Payment', 'Student')", max_length=100)),
                ('model_id', models.IntegerField(help_text='ID of the model instance')),
                ('local_id', models.IntegerField(help_text='Local database ID before sync')),
                ('data', models.JSONField(help_text='Serialized model data')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCING', 'Syncing'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this sync operation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='schools_syn_status_556b41_idx'), models.Index(fields=['model_name', 'model_id'], name='schools_syn_model_n_d0e6c4_idx')],
            },
        ),
    ]
