# Generated by Django 5.2.4 on 2025-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_syncstatus_syncqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='End location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='End location longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Start location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Start location longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Dropoff location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Dropoff location longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Pickup location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Pickup location longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current vehicle latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current vehicle longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Last time location was updated', null=True),
        ),
    ]
