# Generated by Django 5.2.4 on 2025-11-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_route_end_latitude_route_end_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_location_update',
        ),
        migrations.AddField(
            model_name='route',
            name='school_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='School latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='school_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='School longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for end location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for end location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for start location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for start location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for dropoff location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for dropoff location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for pickup location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for pickup location', max_digits=9, null=True),
        ),
    ]
