# Generated by Django 5.2.4 on 2025-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_remove_vehicle_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(choices=[('MAIN', 'Main School'), ('ANNEX', 'Annex School')], default='MAIN', help_text='School location: Main or Annex', max_length=10),
        ),
        migrations.AddField(
            model_name='mealpricing',
            name='location',
            field=models.CharField(choices=[('MAIN', 'Main School'), ('ANNEX', 'Annex School')], default='MAIN', help_text='School location: Main or Annex', max_length=10),
        ),
        migrations.AddField(
            model_name='route',
            name='location',
            field=models.CharField(choices=[('MAIN', 'Main School'), ('ANNEX', 'Annex School')], default='MAIN', help_text='School location: Main or Annex', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(choices=[('MAIN', 'Main School'), ('ANNEX', 'Annex School')], default='MAIN', help_text='School location: Main or Annex', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(choices=[('MAIN', 'Main School'), ('ANNEX', 'Annex School')], default='MAIN', help_text='School location: Main or Annex', max_length=10),
        ),
        migrations.AlterField(
            model_name='mealpricing',
            name='meal_type',
            field=models.CharField(choices=[('TEA_BREAK', 'Tea Break'), ('LUNCH', 'Lunch'), ('FRUITS', 'Fruits')], help_text='Type of meal', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mealpricing',
            unique_together={('meal_type', 'location')},
        ),
    ]
