# Generated by Django 5.2.4 on 2025-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0027_add_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmealpayment',
            name='location',
            field=models.CharField(choices=[('MAIN', 'Main School'), ('ANNEX', 'Annex School')], default='MAIN', help_text='School location: Main or Annex', max_length=10),
        ),
    ]
