# Generated by Django 5.2.4 on 2025-11-27 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_add_location_to_student_meal_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='location',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main School'), ('ANNEX', 'Annex School')], help_text='School location filter', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='recipients_count',
            field=models.IntegerField(default=0, help_text='Number of recipients'),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='recipient_type',
            field=models.CharField(choices=[('ALL_STUDENTS', 'All Students (Parents)'), ('GRADE', 'Students of Specific Grade/Class'), ('LOCATION_MAIN', 'Students of Main School'), ('LOCATION_ANNEX', 'Students of Annex School'), ('FEES_REMINDER', 'All Students with Fees Reminders'), ('ALL_TEACHERS', 'All Teachers'), ('INDIVIDUAL', 'Individual Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='specific_grade',
            field=models.ForeignKey(blank=True, help_text='Required for grade-specific messages', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.grade'),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='specific_student',
            field=models.ForeignKey(blank=True, help_text='Required for individual student messages', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.student'),
        ),
    ]
