# Generated by Django 5.2.4 on 2026-01-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0031_salaryadvance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schools.employee')),
                ('staff_type', models.CharField(choices=[('ADMIN', 'Administrative Staff'), ('SUPPORT', 'Support Staff'), ('SECURITY', 'Security Personnel'), ('MAINTENANCE', 'Maintenance Staff'), ('KITCHEN', 'Kitchen Staff'), ('LIBRARIAN', 'Librarian'), ('LAB_TECH', 'Lab Technician'), ('NURSE', 'School Nurse'), ('DRIVER', 'Driver'), ('CLEANER', 'Cleaner'), ('OTHER', 'Other')], default='SUPPORT', max_length=20)),
                ('job_description', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Direct supervisor (usually head teacher or department head)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_staff', to='schools.employee')),
            ],
            options={
                'verbose_name': 'Non-Teaching Staff',
                'verbose_name_plural': 'Non-Teaching Staff',
                'ordering': ['first_name', 'last_name'],
            },
            bases=('schools.employee',),
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID', 'National ID'), ('CERTIFICATE', 'Certificate'), ('CONTRACT', 'Employment Contract'), ('MEDICAL', 'Medical Report'), ('CLEARANCE', 'Police Clearance'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='staff_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='schools.employee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('HR', 'HR/Admin')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='schools.salaryadvance')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_approvals_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['approval_level', '-created_at'],
                'unique_together': {('advance', 'approval_level')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('HR', 'HR/Admin')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='schools.leave')),
            ],
            options={
                'ordering': ['approval_level', '-created_at'],
                'unique_together': {('leave', 'approval_level')},
            },
        ),
    ]
