# Generated by Django 5.2.4 on 2026-01-24 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_schoolconfig_options_schoolconfig_admin'),
        ('schools', '0034_nonteachingstaff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='branch',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_offices', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='employee',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='expense',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_expenses', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_plans', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='leave',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='mealpricing',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_pricings', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='route',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='studentmealpayment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_payments', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='transportfee',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_fees_records', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='config.schoolconfig'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
