# Generated by Django 5.2.4 on 2026-01-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_schoolconfig_options_schoolconfig_admin'),
        ('schools', '0035_assessment_school_attendance_school_branch_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadvance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='config.schoolconfig'),
        ),
    ]
