# Generated by Django 5.2.4 on 2026-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0036_salaryadvance_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('HOD', 'Head of Department'), ('DEPUTY', 'Deputy Principal'), ('PRINCIPAL', 'Principal'), ('ADMIN', 'Administrative Staff'), ('ACCOUNTANT', 'Accountant'), ('FOOD_MANAGER', 'Food Manager'), ('TRANSPORT_MANAGER', 'Transport Manager'), ('DRIVER', 'Driver'), ('SUPPORT', 'Support Staff')], max_length=20),
        ),
    ]
