# Generated by Django 5.2.4 on 2026-01-26 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_schoolconfig_admission_fee'),
        ('schools', '0037_student_admission_fee_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodfee',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_fees_records', to='config.schoolconfig'),
        ),
    ]
