# Generated by Django 5.2.4 on 2026-01-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0038_foodfee_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='fee_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Send to students with balance below this amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='fee_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Send to students with balance above this amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='specific_employee',
            field=models.ForeignKey(blank=True, help_text='Required for individual staff messages', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.employee'),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='recipient_type',
            field=models.CharField(choices=[('ALL_STUDENTS', 'All Students (Parents)'), ('GRADE', 'Students of Specific Grade/Class'), ('LOCATION_MAIN', 'Students of Main School'), ('LOCATION_ANNEX', 'Students of Annex School'), ('FEES_REMINDER', 'Fees Reminders (with Filters)'), ('ALL_TEACHERS', 'All Teachers'), ('ALL_STAFF', 'All Staff (Teaching & Non-Teaching)'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff Only'), ('INDIVIDUAL', 'Individual Student'), ('INDIVIDUAL_STAFF', 'Individual Staff Member')], max_length=20),
        ),
    ]
