# Generated by Django 5.2.4 on 2026-01-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_schoolconfig_admission_fee'),
        ('schools', '0039_smsmessage_fee_max_smsmessage_fee_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='assessment_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='assessment_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly Assessment'), ('opener', 'Opener Assessment'), ('mid-term', 'Mid-Term Assessment'), ('end-term', 'End-Term Assessment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='recipient_type',
            field=models.CharField(choices=[('ALL_STUDENTS', 'All Students (Parents)'), ('GRADE', 'Students of Specific Grade/Class'), ('LOCATION_MAIN', 'Students of Main School'), ('LOCATION_ANNEX', 'Students of Annex School'), ('FEES_REMINDER', 'Fees Reminders (with Filters)'), ('ASSESSMENT_RESULTS', 'Assessment Results'), ('ALL_TEACHERS', 'All Teachers'), ('ALL_STAFF', 'All Staff (Teaching & Non-Teaching)'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff Only'), ('INDIVIDUAL', 'Individual Student'), ('INDIVIDUAL_STAFF', 'Individual Staff Member')], max_length=20),
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FEES', 'Fees Reminders'), ('RESULTS', 'Assessment Results'), ('GENERAL', 'General Announcements'), ('STAFF', 'Staff Communication')], max_length=20)),
                ('message', models.TextField(help_text='Use placeholders: {student_name}, {parent_name}, {balance}, {results}, {term}, {exam_type}')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_templates', to='config.schoolconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
