# Generated by Django 5.2.4 on 2026-01-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_schoolconfig_admission_fee'),
        ('schools', '0040_smsmessage_assessment_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('school', 'name')},
        ),
    ]
