# Generated by Django 5.2.4 on 2026-01-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_schoolconfig_admission_fee'),
        ('schools', '0041_alter_branch_name_alter_branch_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(choices=[('MATH', 'Mathematics'), ('ENG', 'English'), ('KIS', 'Kiswahili'), ('SCI', 'Science & Technology'), ('SST', 'Social Studies'), ('CRE', 'Christian Religious Education'), ('IRE', 'Islamic Religious Education'), ('HRE', 'Hindu Religious Education'), ('PHE', 'Physical & Health Education'), ('ART', 'Art & Craft'), ('MUS', 'Music'), ('AGR', 'Agriculture')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'admission_number')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('school', 'number', 'year')},
        ),
    ]
