# Generated by Django 5.2.4 on 2026-01-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0042_alter_student_options_alter_student_admission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
