# Generated by Django 5.2.4 on 2026-01-24 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_schoolconfig_options_schoolconfig_admin'),
        ('food', '0002_mealitem_per_serving_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstudentaccount',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_accounts', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='foodsubscription',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_subscriptions', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='foodtransaction',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_transactions_list', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='config.schoolconfig'),
        ),
    ]
