"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Load environment variables from .env file if it exists
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv not installed, continue without .env support

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-d8tc3m9u-r3=!4bdc^it^k*-dvqqkh^+&(7d$=61&4nb-g&vsx')

import sys

# SECURITY WARNING: don't run with debug turned on in production!
# Smart detection: Debug is True if explicitly set to 'True' OR if running locally via runserver
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true' or 'runserver' in sys.argv

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',') if os.environ.get('ALLOWED_HOSTS') else [
    'auth-system.bdmis.co.ke',
    'edumanage.bdmis.co.ke',
    'www.edumanage.bdmis.co.ke',
    'edumanage.keyroacademy.top',
    'www.edumanage.keyroacademy.top',
    'uniqo.top',
    'www.uniqo.top',
    'localhost',
    '127.0.0.1',
    '*'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',
    'schools',
    'schools.templatetags',
    'config',
    'widget_tweaks',
    'finance',
    'food',
    'transport',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'schools.middleware.OfflineDetectionMiddleware',  # Offline detection - Disabled for performance
]

ROOT_URLCONF = 'school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'frontend/dist')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.mysql'),
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'CONN_MAX_AGE': 300, # Keep connections alive for 5 minutes
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # For collectstatic

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets_source'),  # This is where your app's static files live
    os.path.join(BASE_DIR, 'frontend/dist'),  # React build files
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#STATIC_URL = '/static/'
#STATICFILES_DIRS = [
#    BASE_DIR / 'school' / 'static',
#]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'  # Redirect to frontend login route
LOGIN_REDIRECT_URL = '/dashboard'  # After successful login, redirect here
LOGOUT_REDIRECT_URL = '/login/'  # After logout, redirect here

#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Security settings
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Additional security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CSRF Trusted Origins for production
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Add production domain to CSRF trusted origins if not in DEBUG mode
# Add production domain to CSRF trusted origins if not in DEBUG mode
if not DEBUG:
    # Add your production domain
    CSRF_TRUSTED_ORIGINS.extend([
    'https://edumanage.bdmis.co.ke',
    'https://www.edumanage.bdmis.co.ke',
    'http://edumanage.bdmis.co.ke',
    'https://auth-system.bdmis.co.ke',
    'http://auth-system.bdmis.co.ke',
    'https://edumanage.keyroacademy.top',
    'https://www.edumanage.keyroacademy.top',
    'https://uniqo.top',
    'https://www.uniqo.top',
    ])

# CORS Configuration
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# CSRF Cookie settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False

# CSP settings
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "https://cdn.jsdelivr.net",
    "https://code.jquery.com",
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js",
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://cdn.jsdelivr.net",
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css",
)
CSP_FONT_SRC = (
    "'self'",
    "data:",
    "https://cdn.jsdelivr.net",
)
CSP_IMG_SRC = (
    "'self'",
    "data:",
    "https:",
)
CSP_CONNECT_SRC = (
    "'self'",
    "https://maps.googleapis.com",
    "https://*.googleapis.com",
)
CSP_FRAME_SRC = (
    "'self'",
    "https://www.google.com",
    "https://maps.google.com",
    "https://*.google.com",
)

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Use SMTP for production, or 'django.core.mail.backends.console.EmailBackend' for development
EMAIL_HOST = 'smtp.gmail.com'  # SMTP server (Gmail: smtp.gmail.com, Outlook: smtp-mail.outlook.com, etc.)
EMAIL_PORT = 587  # Port for TLS (587) or SSL (465)
EMAIL_USE_TLS = True  # Use TLS encryption (True for port 587, False for port 465 with SSL)
EMAIL_HOST_USER = 'keyrooperations@gmail.com'  # Your email address (e.g., noreply@bishopdrmandointernationalschool.org)
EMAIL_HOST_PASSWORD = 'vtao xyut pxzu qzbi'  # Your email password or app-specific password
DEFAULT_FROM_EMAIL = 'keyrooperations@gmail.com'  # Default sender email address

# WhatsApp Business API Configuration (Meta)
WHATSAPP_PHONE_NUMBER_ID = '864197766778782'  # Your WhatsApp Business Phone Number ID
WHATSAPP_ACCESS_TOKEN = 'EAAQWxxIZBvJMBQFkVyRuCNQjsRNdi3MqaqsAh9S6ZBzlPPb8Xp7O4XZCK1WFWySRlj7XknOQvJCT2wkzzg9AfCZBVLmZBJhzx94FHDcjZCvnr7zHjDRIXdF7VAEjrWxuRsVEOl81NZBiRwIHp1wubaQfGG7qwPT3NqwNa9jg8wVvlEWWiMu1ZALFymCiP6ClsYyjgLHDPbUYlEiybE7kQGmHH6C5r5Xg0HqgzmtQdEH9hGqacnmhhdQVe5ZCze9Qjc52GnLux0ZBEUsQsAJkp9lfB514mZC'  # Your WhatsApp Business API Access Token
WHATSAPP_BUSINESS_ACCOUNT_ID = '850700390692147'  # Your WhatsApp Business Account ID
WHATSAPP_API_VERSION = 'v22.0'  # WhatsApp API version (default: v22.0)

# SMS Configuration - Termii
# Get your credentials from: https://termii.com/
TERMII_API_KEY = os.environ.get('TERMII_API_KEY', 'TLpGzVEJOSPadznWDVIYIozvYSbaoFYqeDyhmsFLFZoZAsZDCPMlfskkUIXkII')  # Your Termii API key
TERMII_SENDER_ID = os.environ.get('TERMII_SENDER_ID', 'Edumanage')  # Your sender ID (alphanumeric, max 11 characters)


MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


# M-Pesa Configuration
MPESA_ENVIRONMENT = 'sandbox'
MPESA_CONSUMER_KEY = 'svhVXSfDkeudk5abSGKcSh5PAvHq91tMCVj56nAACr20J0Nk'
MPESA_CONSUMER_SECRET = 'dETs62YsA0VxDYqeqwVrD8KGiJnGdjysS5AegESubrR9h65EoDBhum9qlcUlPyo3'
MPESA_SHORTCODE = '174379'  # Standard test shortcode for sandbox
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'  # Standard test passkey for sandbox
MPESA_CALLBACK_URL = 'https://api.theransomedschools.org/mpesa/callback/'  # Update this with your actual domain

# Google Maps API Configuration
# Get your API key from: https://console.cloud.google.com/google/maps-apis
# Enable: Maps JavaScript API, Directions API, Geocoding API, Places API
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', 'AIzaSyDXwxd0wlWa5pJEBN_glRwD5O2asF9WrHA')


# Update CSP settings
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "https://cdn.jsdelivr.net",
    "https://code.jquery.com",
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js",
) 
# WhiteNoise Configuration for Static Files
if DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True
else:
    # Production: Use non-manifest storage to avoid 404s on missing hash maps
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Paystack Configuration
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', 'sk_test_default_key_replace_in_prod')
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', 'pk_test_default_key_replace_in_prod')

# SSL Proxy Header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Logging configuration - Reduced verbosity in production for performance
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING' if not DEBUG else 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': 'WARNING' if not DEBUG else 'DEBUG',
            'propagate': True,
        },
        # Suppress common noisy logs in production
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['file'],
            'propagate': False,
        },
    },
}
