# Generated by Django 5.2.4 on 2026-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Google Maps embed iframe code', null=True),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='pickup_location_embed',
            field=models.TextField(blank=True, help_text="Google Maps embed code for student's pickup location", null=True),
        ),
    ]
