# Generated by Django 5.2.4 on 2026-01-13 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_route_map_embed_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(help_text='e.g. Toyota Coaster', max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'In Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(blank=True, help_text='Primary route assigned to this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.route')),
            ],
        ),
        migrations.CreateModel(
            name='TransportDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('vehicle', models.OneToOneField(blank=True, help_text='Vehicle currently assigned to this driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='transport.transportvehicle')),
            ],
        ),
    ]
