# Generated by Django 5.2.4 on 2026-01-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transportdriver_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportassignment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
