# Generated by Django 5.2.4 on 2026-01-24 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_schoolconfig_options_schoolconfig_admin'),
        ('transport', '0006_transportadvancerequest_transportexpense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='transportadvancerequest',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_driver_advances', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='transportdriver',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_drivers', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='transportexpense',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_expenses', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='transportleaverequest',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_driver_leaves', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='transportstudentaccount',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_accounts', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='transporttransaction',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_transactions', to='config.schoolconfig'),
        ),
        migrations.AddField(
            model_name='transportvehicle',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_vehicles', to='config.schoolconfig'),
        ),
    ]
